### PR TITLE
Emulate Belkin socket for Alexa Discovery

### PR DESCRIPTION
**Pull request by imduffy15**
This commit adds support for Valetudo to automatically be picked up by Alexa's device discovery.

Valetudo exposes a SSDP discovery response that emulates a Belkin smart plug. This approach is used in various open source smart home solutions such as https://github.com/arendst/Tasmota and https://github.com/n8henrie/fauxmo

With the option enabled, "alexa, discover devices" should automatically pick up your valetudo device and allow you to start/stop cleaning by saying "Alexa turn on/off roborock".

Ideally, I would love if we could automatically generate different switches for all the different zones and/or rooms. However, I'm not seeing an easy way to do this beyond exposing lots of SSDP servers.

### CODE REVIEW

**Comment by imduffy15** [comment]
Reworked to expose a unique ssdp and http server for each zone.

**Comment by imduffy15** [comment]
I am now running this on my own vacuum, no issues so far. Built it using https://github.com/zvldz/vacuum

**Comment by Wee20x** [comment]
I would love top have this Feature in an official Release. It would be nice to have an Option to choose the zones which are exposed to Alexa.

**Comment by Wee20x** [comment]
@rand256 

Could you consider merging this pull request ?

**Comment by imduffy15** [comment]
Would still be nice but there doesn't seem to be any interest so closing.

**Pull request closed without merging**
